apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Release.Name }}
  labels:
    app: gitops-platform
    environment: {{ .Values.app.environment }}

spec:

  replicas: {{ .Values.replicaCount }}

  strategy:

    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:

    matchLabels:
      app: {{ .Release.Name }}

  template:

    metadata:

      labels:
        app: {{ .Release.Name }}
        environment: {{ .Values.app.environment }}

    spec:

      serviceAccountName: {{ .Release.Name }}

      containers:

      - name: flask-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:

        - containerPort: 5000

        envFrom:

        - configMapRef:
            name: {{ .Release.Name }}-config

        - secretRef:
            name: {{ .Release.Name }}-secret

        readinessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 20

        resources:

          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
